### ISSUE TITLE
Add mapping for discount code information

### ISSUE THREAD

**Issue by mmoelli** [sphereio/sphere-order-export#28]
For the header ```discountCodes``` the CSV cell should be filled with all applied discount codes at this cart, separated with the multi value delimiter.

```
Super-Duper;10PERCENT;FREESHIPPING
```

**Comment by PhilippSpo** [comment]
> separated with the multi value header

you mean delimiter?

**Comment by mmoelli** [comment]
yes, sorry for that.

**Comment by PhilippSpo** [comment]
@mmoelli Should all discount codes be displayed, no matter what `DiscountCodeState`?

**Comment by mmoelli** [comment]
Hmm, as far as I remember, in the order can only have discount codes which matches the cart. If a discount code does not match, you cannot order this cart. So they should be only on possible value for the state.

cc @agourlay @OlegIlyenko

**Comment by OlegIlyenko** [comment]
Indeed, one can order a cart only if all discount codes are valid and match the cart. After order creation we do not recalculate the discounts, so the state should remain frozen after the checkout. @agourlay  Maybe we should consider different model for cart and order to avoid the confusion

**Comment by PhilippSpo** [comment]
@OlegIlyenko would be helpful for sure. Thanks for the explanation :+1: 
@mmoelli so the current implementation is fine since it just ignores the `DiscountCodeState`, right?
