### ISSUE TITLE
doc / README:  state clearly whether the CSV has a line per order or per line item

### ISSUE THREAD

**Issue by nkuehn** [sphereio/sphere-order-export#32]
It's somewhat unclear without trying out whether the CSV export is exporting a line per order line item or a line per order or dynamically depending on whether a `lineItems.*`  column is requested or not.

**Comment by wizzy25** [comment]
@nkuehn This is already clearly stated in the [readme](https://github.com/sphereio/sphere-order-export/blame/master/README.md#L71) 
Cc @hisabimbola

**Comment by nkuehn** [comment]
my fault. I think I oversaw it because it's formatted as a light grey citation and not as normal text.   anyhow, sorry.
