### ISSUE TITLE
Export deliveries and parcels in shippingInfo on Order level

### ISSUE THREAD

**Issue by VasumathiJayakumar** [sphereio/sphere-order-export#36]
The "deliveries" in "shippingInfo" on Order level should be exported to csv file

**Comment by junajan** [comment]
Based on the [documentation](http://dev.commercetools.com/http-api-projects-orders.html#delivery), the `deliveries` is an array of delivery items containing:
 - an array of deliveryItems: {lineItemId, quantity}
 - an array of parcels: {id, createdAt, measurements:object, trackingData:object}

We should serialize this array into one single CSV cell. The simplest way would be to use JSON.stringify and flush it as a JSON string 🤔. What do you think @wizzy25 @hisabimbola?

**Comment by VasumathiJayakumar** [comment]
@hisabimbola any update on this?

**Comment by Oehmi** [comment]
@hisabimbola 
only trackingID is needed

**Comment by junajan** [comment]
@VasumathiJayakumar - recently we added deliveries order csv parser here https://github.com/commercetools/csv-parser-orders/pull/18

So this order shippingInfo export should follow the same structure as the parser does.

**Comment by VasumathiJayakumar** [comment]
@junajan Thanks for the information. I will test this now.

**Comment by wizzy25** [comment]
This seems like a good way to go 🙂

**Comment by hisabimbola** [comment]
@wizzy25 what seems like a good way to go

There are two options 🙄
