### ISSUE TITLE
Add parameter for filtering orders

### ISSUE THREAD

**Issue by junajan** [sphereio/sphere-order-export#42]
Add a CLI parameter which will work as a predicate to filter only selected orders.

**Comment by Siilwyn** [comment]
Let's call it `where` to make it really obvious that it's for the predicate of the HTTP API.

**Comment by junajan** [comment]
We found out that except the `_fetchOrders` there is also `runCSVAndStreamToFile` function which loads data from Sphere and thus it should have also this `where` parameter implemented.
