### ISSUE TITLE
Add option to fill all rows with general order information

### ISSUE THREAD

**Issue by Oehmi** [sphereio/sphere-order-export#47]
In the order export, we should offer an option to fill all rows of an order with the _general order information_, instead of just the first row of an order.

Background: Currently, the 1st row in the order export contains general information such as address; in the 2nd row per order are all the line items of the order. The general rows are not filled because they are redundant, but some of our customers would like them to always be filled.

**Comment by junajan** [comment]
The first row of the order with lineItems contains basic (order level) info like addresses, prices, etc.
If we put this info also to other rows, should we remove the first row because of a redundancy? 

What do you think @Siilwyn @hisabimbola?

**Comment by Siilwyn** [comment]
I think we shouldn't add more options and instead fill them all as a default behaviour unless there is a huge benefit that I'm missing. The redundancy is not that big of a problem imho.

**Comment by hisabimbola** [comment]
We should not remove the first row, but I am not sure whether we should do this without a flag, what if some users do not want the redundant rows 🙄

**Comment by junajan** [comment]
I added here https://github.com/sphereio/sphere-order-export/issues/48 a `--fillAllRows` parameter which will add this behavior.

**Comment by Siilwyn** [comment]
I'll just leave this here: https://www.youtube.com/watch?v=glZ1C-Yu5tw
^^
:wave:
