### ISSUE TITLE
Support delivery info

### ISSUE THREAD

**Issue by Oehmi** [sphereio/sphere-order-export#50]
We would like to support the update actions "add deliveries".
(see https://dev.commercetools.com/http-api-projects-orders.html#add-delivery)

Due to the complexity of the delivery object, we are not able to structure an easy-to-use csv format. We have suggested a new structure for this (see possible solution).

_GroupByDelivery, ItemID, quantity and parcel.id_ are mandatory fields.

### Current Behavior
Not supported currently

### Possible Solution
There could be a GroupByDeliveryID which is only there to separate the deliveries from each other. So all line items with the same GroupByDeliveryID belongs to the same Delivery.
Inside this, the parcelID is available to separate the parcels from each other.
Clarify: Dies the ID have to be unique over all parcels or just inside the delivery?

**Comment by hisabimbola** [comment]
This is the wrong repo, correct repo [here](https://github.com/commercetools/orders-update/issues/14)
