### ISSUE TITLE
Order Export file Not found

### ISSUE THREAD

**Issue by abernhar** [sphereio/sphere-order-export#58]
### Description
Using the order export with a csv template. I think the export is working correctly but if you want to download the file, you get an error message "Not found".

### Expected Behavior
It should be possible to download the order export

### Current Behavior
Error message not found is shown

### Context
Support ticket

**Comment by junajan** [comment]
Hello,
I am investigating this issue and so far I found these things:
1. Impex is using this command to export orders:
```bash
~$ /app/node_modules/.bin/order-export --projectKey 'coeur-staging' --accessToken '-----' --csvTemplate '/app/1501148497457_orders-tpl.csv' --csvFile '/app/tmp-18NYK8QtgJUevZ/exported-orders.csv' --exportCSVAsStream --logSilent --sphereHost 'api.sphere.io' --sphereProtocol 'https'
```

I looked to history and in the supported parameters there is missing `--csvFile`.
