### ISSUE TITLE
Remove lookup of unavailable customObject reference

### ISSUE THREAD

**Issue by ValeSauer** [sphereio/sphere-order-export#60]
https://github.com/sphereio/sphere-order-export/blob/320103142285b7e7526cfe0c2814f1d3c36384d8/src/coffee/orderexport.coffee#L139-L143

This and the following lines seems to contain some project-specific business logic where there was an additional customObject containing payment info for every cart required. This is not the case in all other projects. Remove it?

**Comment by hisabimbola** [comment]
Yeah, we probably need to remove it. Thanks for reporting @ValeSauer we will investigate this and prioritise accordingly
