### ISSUE TITLE
The Order Exporter fails due to creating temp dirs exceeding the 255-character filename limit.

### ISSUE THREAD

**Issue by michael-s-grant** [sphereio/sphere-order-export#62]
### Description
The Order Exporter creates very long directory names, including spurious JavaScript code, which exceed the 255-character filename limit; this causes it to fail.

### Expected Behavior
Temporary directories should have names of the form '/tmp/tmp-7191EAcLrQidQ/'.

### Current Behavior
Temporary directory names currently have JavaScript callback code embedded in them; actual example:
```js
/tmp/tmp-7191EAcLrQidQ,function _cleanupCallback(next) {
    if (!called) {
        var index = _removeObjects.indexOf(_cleanupCallback);
        if (index >= 0) {
          _removeObjects.splice(index, 1);
        }

        called = true;
        removeFunction(arg);
    }
    if (next) next(null);
  }/
```

### Context
This breaks my team's CSV Connector order export jobs on iron.io.

I don't understand why the problem is only making itself manifest now.

### Possible Solution

I have tracked down the problem to l. 57 in ensureExportDir() in src/coffee/run.coffee.  The call to tmp.dirAsync is being treated, when it is used at l. 129 onwards, as if it returned (a promise of?) a directory name, but in fact it returns (a promise of?) a two-element list, consisting of the directory name and a callback.  When this list is used as a string, the string representation of the callback is included in it.  Returning only the first element of the list would fix the problem.

I have not verified whether this affects the return values at lines 63 or 66 too, but I don't think it does.

**Comment by wizzy25** [comment]
Thanks for catching this bug. Will be resolved accordingly
