### ISSUE TITLE
Export of discountCodes fails if discountCode is deleted

### ISSUE THREAD

**Issue by ValeSauer** [sphereio/sphere-order-export#63]
Export of discountCodes fails if discountCode is deleted. The solution that I propose here https://github.com/sphereio/sphere-order-export/pull/64 does simply remove the discountCode from the export.
Perhaps it is better to export something else instead, like code.id or string "code_deleted" . ?

`   { body: undefined,
     message: 'Cannot read property \'code\' of undefined',
     name: 'TypeError',
     stack: 'TypeError: Cannot read property \'code\' of undefined\n    at /app/node_modules/sphere-order-export/lib/mapping-utils/csv.js:119:34\n    at Function._.map._.collect (/app/node_modules/underscore/underscore.js:172:24)\n    at formatDiscountCodes (/app/node_modules/sphere-order-export/lib/mapping-utils/csv.js:117:14)\n    at CsvMapping._getValue (/app/node_modules/sphere-order-export/lib/mapping-utils/csv.js:70:25)\n    at /app/node_modules/sphere-order-export/lib/mapping-utils/csv.js:42:22\n    at Function._.map._.collect (/app/node_modules/underscore/underscore.js:172:24)\n    at CsvMapping._mapOrder (/app/node_modules/sphere-order-export/lib/mapping-utils/csv.js:40:17)\n    at /app/node_modules/sphere-order-export/lib/orderexport.js:132:39\n    at Function._.map._.collect (/app/node_modules/underscore/underscore.js:172:24)\n    at _this.client.orders.expand.expand.expand.expand.perPage.process.accumulate (/app/node_modules/sphere-order-export/lib/orderexport.js:131:22)\n    at /app/node_modules/sphere-node-sdk/lib/services/base.js:267:20\n    at tryCatcher (/app/node_modules/sphere-node-sdk/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/sphere-node-sdk/node_modules/bluebird/js/main/promise.js:503:31)\n    at Promise._settlePromiseAt (/app/node_modules/sphere-node-sdk/node_modules/bluebird/js/main/promise.js:577:18)\n    at Promise._settlePromises (/app/node_modules/sphere-node-sdk/node_modules/bluebird/js/main/promise.js:693:14)\n    at Async._drainQueue (/app/node_modules/sphere-node-sdk/node_modules/bluebird/js/main/async.js:123:16)\n    at Async._drainQueues (/app/node_modules/sphere-node-sdk/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/sphere-node-sdk/node_modules/bluebird/js/main/async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:396:17)',
     code: undefined,
     statusCode: undefined,
     signal: undefined },
  project_key: '***' } 'Oops, something went wrong!'`

**Comment by Oehmi** [comment]
@ValeSauer For questions of prioritising this issue: Is this occuring very often that a discount code is deleted?

**Comment by ValeSauer** [comment]
This issue occurred twice in three months at Dodenhof. The reason is that they need to create a monthly report about the usage of discountCode in the last month for their marketing. I don't know of similar support requests from other customers. My workaround for now is that I run the modified version of the application i suggested here https://github.com/sphereio/sphere-order-export/pull/64/commits/29f4857fdb55476991e923bff68f2634a726a795 locally and send the export by email to dodenhof. The reason this is not solved yet is because we have a hard time finding a decision about the behavior of the export when a discount code has been deleted. This is probably something you has PO has to decide.

**Comment by Oehmi** [comment]
@ValeSauer 
Update: We discussed with @wizzy25 and won't solve this for now with adding eg. "code_deleted" to those discount codes deleted; and considering that there's a current workaround for one customer needing it on only a monthly basis. I'm not aware of other customers that have had the same issue. 
Our suggestion is to put this to the Backlog for now, and to pick it up again when we have more time. 
FYI @wizzy25
